---
title: "R Notebook"
output: html_notebook
---

```{r,warning=FALSE}
library(TSA)
library(forecast)
library(tseries)
data = read.csv('orders.csv')
source('functions.R')
library(fGarch)
```

Données : 308 jours (44 semaines) à partir du 4 janvier 2021
```{r}
timeSeries = ts(data$n_orders, frequency=7)
plot(timeSeries, type='l')
```

Données d'entrainement
```{r}
timeSeriesTest = ts(data$n_orders[281:308], start = 41, frequency=7)
timeSeries = ts(data$n_orders[1:280], frequency=7)
plot(timeSeries, type='l')
```

```{r}
X = diff(diff(log(timeSeries),7))
plot(X, type="l")
check_stat(X)
```
```{r}
acf(as.numeric(X), lag.max = 40)
pacf(as.numeric(X), lag.max = 40)
```
On tente sur la série de base
```{r}
mod1 = garchFit(data=timeSeries)
summary(mod1)
plot(timeSeries)
lines(ts(fitted(mod1), start=1, frequency=7),col='red',type='l')

```



Erreur finale
```{r}
pred = predict(object=mod1, n.ahead=28, plot=TRUE)

#pred_val = pred$meanForecast

#MAPE = 100/28*sum(abs((pred_val-timeSeriesTest))/pred_val)
#MAPE
```